### ISSUE TITLE
When I run the .exe, the .exe immediately closes.

### ISSUE THREAD

**Issue by DrewNeilson** [mrene/minidsp-rs#192]
I don't know if I'm opening it correctly. Does it work if the MiniDSP application is also running, and does it matter whether or not that application is connected to my MiniDSP? I've got minidsp-rs listed in the settings for BEQ Designer, and maybe BEQ Designer is using it, and that's why minidsp-rs won't stay open. However, I've already tried running minidsp-rc without BEQ Designer running, and minidsp-rc won't stay open.
I got it by downloading "minidsp.x86_64-pc-windows-msvc.zip" earlier this week.
My MiniDSP is a DDRC-24 running firmware version 1.14. It's connected via USB to my Windows 10 PC. Its Windows application version is 1.11. Windows 10 is up to date.

**Comment by mrene** [comment]
`minidsp.exe` is a console application, which means it must be opened via a command prompt (usually cmd.exe, or powershell.exe) in order to be used. Windows unfortunately flashes a console and immediately closes it if you try to open it from the UI.

BEQDesigner will spawn minidsp.exe on its own, with some extra arguments, in order to set the right filter values.

**Comment by DrewNeilson** [comment]
Is it possible, then, for me to create a .bat file that opens MiniDSP.exe, runs whatever commands I tell it to, and keeps the window open so that I can read it?
