### ISSUE TITLE
Couple of naive questions (to be added in documentation ?)

### ISSUE THREAD

**Issue by rfenouil** [mrene/minidsp-rs#199]
Hello and thank you for this tool.

I have a couple of very naive questions regarding this tool.
Maybe this could be clarified in the early pages of documentation. My apologies if it is already there but I did not find it.

Question 1:
I have a minidsp SHD and I initially assumed your tool uses the provided websocket interface to control it but I doubt it now.
Does your tool work only on usb-connected devices or can it connect to remote devices through network ?

Question 2:
How does your tool work (communication with device), and how did you manage to get initial documentation to create it (device connection protocol, commands) ? 
Did you have to reverse-engineer communication protocol between devices and configuration application ?

Question 3:
Are you affiliated with minidsp ? Is your tool going to be promoted/supported by them at some point ?

Thank you for your answers !

**Comment by mrene** [comment]
Hi!

1. It can work with both local (usb-hid) and remote (tcp) devices, there has been some report of people using with with an SHD, and I would expect auto-discovery to work if you run `minidsp probe --net`.  I wasn't aware of any websocket interface to their products, if there is, I'd be interested in seeing some packets to look at.

2. The devices use USB HID reports in order to exchange commands and responses. The official apps are written using Adobe Air, with no USB support, so there is a small app that proxies HID frames to the application via TCP. Their WI-DI appliance uses the same protocol.  This makes it fairly trivial to sniff packets and inspect what commands are sent. I looked at some flash disassembly and at the code for their (web) app on iOS, but once I figured out the main patterns it generalized pretty well. For example, most settings have an address that's referenced in the xml config file and there is a single command to write a value to these addresses (some exceptions apply - you can find [most of the protocol here](https://github.com/mrene/minidsp-rs/blob/dev/protocol/src/commands.rs#L189)

3. No affiliation what-so-ever. I had a proof of concept in node a few years back and saw it brought value to people so I expanded on it. They are aware of its existance and they've publically referenced this project in their newsletter. Overall they are supportive of it and happy that it cathers to a DIY audience without having to spend engineering resources maintaining it.

**Comment by rfenouil** [comment]
Hi, thank you for the detailed answers, very interesting !

I did not understand this usb transport technology, thank you for making this clearer.
I now understand that the tool is not designed to detect the SHD directly via its ethernet interface, but to be used with miniDG that forwards usb connection... That's why I did not manage to detect my device :)

You did an awesome job with this project, congrats and thank you very much for making this publicly available.
